project:
  type: website
  output-dir: "docs"
website:
  title: "Zoe Fairlie"
  page-footer: "© 2025 Zoe Fairlie"
  navbar:
    background: "#F5FFFA"
  sidebar:
    style: "floating"
    pinned: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: "Home"
      - href: Resume.qmd
        text: "Resume"
      - section: "Past Projects"
        contents:
          - href: eco_work.qmd
            text: "Work at ECO Northwest"
          - href: Website.qmd
            text: "Senior Honors Thesis"
          - href: birdproject.qmd
            text: "SPUR Grant Research Project"
      - href: Pictures.qmd
        text: "Pictures"
format:
  html:
    theme: lux
    css: style.css
    mainfont: Garamond
    toc: true
    toc-depth: 1
    smooth-scroll: true
    code-fold: true
