project:
  type: website
  resources:
    - google02da4d596b6bb338.html
  output-dir: "docs"
website:
  title: "Zoe Fairlie"
  site-url: https://zoefairlie.github.io
  description: "Zoe Fairlie is a quantitative researcher and PhD student studying the effects of human activities on wildlife."
  page-footer: "© 2025 Zoe Fairlie"
  navbar:
    background: "#F5FFFA"
  sidebar:
    style: "floating"
    pinned: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: "Home"
      - href: Resume.qmd
        text: "Resume"
      - section: "Past Projects"
        contents:
          - href: Website.qmd
            text: "Senior Honors Thesis"
      - href: Pictures.qmd
        text: "Pictures"
format:
  html:
    theme: lux
    css: style.css
    mainfont: Garamond
    toc: true
    toc-depth: 1
    smooth-scroll: true
    code-fold: true
